name: Generate GitHub Stats

on:
  # Run daily at 00:30 UTC
  schedule:
    - cron: "30 0 * * *"

  # Allow manual trigger
  workflow_dispatch:

  # Run on push to main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate GitHub Stats
        uses: jstrieb/github-stats@master
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          EXCLUDED_LANGS: "html,tex"

      - name: Commit and push stats
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add generated/
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update GitHub stats [skip ci]" && git push)
