name: Generate Snake Animation

on:
  # Runs at 00:00 UTC every day
  schedule:
    - cron: "0 0 * * *"

  # Allows manual trigger
  workflow_dispatch:

  # Runs on every push to main branch
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Generate snake animation
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg?palette=github-light
            dist/snake-dark.svg?palette=github-dark

      # Push the generated files to the output branch
      - name: Push Snake to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
